### ISSUE TITLE
More Button functionality not working as expected

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#172] opened 2024-11-19 05:12 UTC
Description: upon searching a game, when click on share button and press more, it redirects to youtube game trailer. As far as i think, that shouldn't be the functionality. Upon clicking more, it should give us more options to share. 

Details requested by TA are as below:

1. Account Used: 
Username: rohan.test1
Password: rohan1234

2. Error: Share button not working as expected. It redirects to youtube showing game trailer. Instead, there should be more options of sharing.

3. Steps Followed:
(a) Searched Battledfield in search bar
(b) Clicked on [Battlefield 1: Standard Collector's Edition](https://www.igdb.com/games/battlefield-1-standard-collectors-edition) (2016)
(c) Clicked on share button present over the youtube trailer box. 
(d) Clicked more -----> [ERROR] unexpected functionality
Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/game-search/game/112637/

4. Expected: Instead, there should be more options of sharing.
<img width="1470" alt="Screenshot 2024-11-19 at 12 08 32 AM" src="https://github.com/user-attachments/assets/b78a7fa0-273e-4d51-ac60-d5474b3a78c2">
<img width="1470" alt="Screenshot 2024-11-19 at 12 10 00 AM" src="https://github.com/user-attachments/assets/ec787d3a-8762-4e45-81d5-1e69f20e425a">
<img width="1470" alt="Screenshot 2024-11-19 at 12 10 54 AM" src="https://github.com/user-attachments/assets/4d246407-9a8c-4894-b487-45882e787450">

**Comment by ad6641** [comment] 2024-11-19 22:09
the video is a youtube video embed - anything on that is what youtube has implemented for their embed video feature, and not something we have done or can modify. so this is expected behavior!
closing this since this isn't a bug / enhancement on our app!

**Closed as completed** 2024-11-23 15:22 UTC
Labels: wontfix, Testing Party
